packageExtensions:
  vitest@*:
    dependencies:
      rollup: '*'
  vite@*:
    dependencies:
      '@types/node': '*'
  local-pkg@*:
    dependencies:
      '@vitest/coverage-c8': '*'

yarnPath: .yarn/releases/yarn-4.1.0.cjs
